# Generated by Django 2.2.14 on 2022-04-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Football'), ('B', 'Basketball'), ('S', 'Swimming'), ('H', 'Hentball'), ('T', 'Tennis'), ('V', 'Volleyball')], max_length=2),
        ),
    ]
